# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kategoriview.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 457)
        self.kategori = QtWidgets.QWidget(MainWindow)
        self.kategori.setObjectName("kategori")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.kategori)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 50, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.kategori)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 140, 441, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonInsert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        self.horizontalLayout.addWidget(self.pushButtonInsert)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.kategori)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 50, 271, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditID = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditID.setObjectName("lineEditID")
        self.verticalLayout_2.addWidget(self.lineEditID)
        self.lineEditKategori = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditKategori.setObjectName("lineEditKategori")
        self.verticalLayout_2.addWidget(self.lineEditKategori)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.kategori)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(40, 210, 441, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget_3)
        self.tabWidget.setObjectName("tabWidget")
        self.NameKategori = QtWidgets.QWidget()
        self.NameKategori.setObjectName("NameKategori")
        self.tabWidget.addTab(self.NameKategori, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.labelResult = QtWidgets.QLabel(self.kategori)
        self.labelResult.setGeometry(QtCore.QRect(40, 190, 35, 10))
        self.labelResult.setObjectName("labelResult")
        self.pushButtonLoad = QtWidgets.QPushButton(self.kategori)
        self.pushButtonLoad.setGeometry(QtCore.QRect(40, 390, 441, 17))
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        MainWindow.setCentralWidget(self.kategori)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButtonInsert.clicked.connect(self.insertkategori)
        self.pushButtonLoad.clicked.connect(self.loadkategori)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
    def insertkategori(self):
        try:
            mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="db_penjualan"
            )
            cursor = mydb.cursor()
            idkat = self.lineEditId.text()
            namekat = self.lineEditName.text()
            sql = "INSERT INTO kategori (id,name) VALUES (%s,%s)"
            val = (idkat,namekat)
            cursor.execute(sql,val)
            mydb.commit()
            self.labelResult.setText("Data Kategori Berhasil Disimpan")

            self.lineEditId.setText("")
            self.lineEditName.setText("")
        except mc.Error as e:
            self.labelResult.setText("Data Kategori Gagal Disimpan")
                
    def loadkategori(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_penjualan"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM kategori ORDER BY ID ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,column_number, QTableWidgetItem(str(data)))
            self.labelResult.setText("Data Kategori Berhasil Ditampilkan")
        except mc.Error as err:
            self.labelResult.setText("Data Kategori Gagal DiLoad")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ID Kategori"))
        self.label_2.setText(_translate("MainWindow", "Nama Kategori"))
        self.pushButtonInsert.setText(_translate("MainWindow", "INSERT DATA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.NameKategori), _translate("MainWindow", "No"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Nama Kategori"))
        self.labelResult.setText(_translate("MainWindow", "TextLabel"))
        self.pushButtonLoad.setText(_translate("MainWindow", "LOAD DATA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
